# Generated by Django 4.0.3 on 2022-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_alter_comments_author_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('restricted', 'restricted'), ('all', 'all'), ('all', 'all')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('auteur', 'Auteur'), ('responsable', 'Responsable'), ('contributeur', 'Contributeur')], default='auteur', max_length=20),
        ),
    ]
