# Generated by Django 4.0.3 on 2022-03-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_alter_contributors_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('auteur', 'auteur'), ('responsable', 'responsable'), ('contributeur', 'contributeur')], default='auteur', max_length=20),
        ),
    ]
