# Generated by Django 4.0.3 on 2022-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_alter_contributors_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
